#server配置
server:
  port: 8080
  servlet:
    context-path: /hial
spring:
  application:
    name: hial
  #session配置
  session:
    timeout: 1800
  #开发工具配置
  devtools:
    restart:
      enabled: false
  #数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hial?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        min-idle: 4
        max-idle: 8
    timeout: 30000
  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    cache: false
#mybatis配置
mybatis:
  type-aliases-package: com.sly.accountmanager.account.model
  mapper-locations:
  - classpath:mapper/**/*.xml
#日志配置
logging:
  level:
    root: info
    web: info
    org.springframework.jdbc: debug
    org.mybatis.spring: debug
  file: D:/logs/hial/hial.log
